In [2]:
import numpy as np

In [3]:
x = np.array([[0,0], [0,1], [1,0], [1,1]])
y = np.array([[0, 0, 0, 1]]).T
x.shape, y.shape

((4, 2), (4, 1))

In [5]:
def sig(z):
    return 1/(1+ np.exp(-z))

In [6]:
def derivativeSig(z):
    return sig(z)*(1-sig(z))

In [10]:
weights =2* np.random.random((2,1))  -1
bias = 2 * np.random.random(1) - 1
lr = 0.1
weights, bias

(array([[0.97393695],
        [0.05161523]]), array([0.06226284]))

In [8]:
for iter in range(10000):
    output0 =x
    output = sig(np.dot(output0, weights)+bias)

    first_term = output - y
    input_for_last_layer = np.dot(output0, weights)+bias
    second_term = derivativeSig(input_for_last_layer)
    first_two_term_from_error = first_term * second_term

    changes = np.array([[0.0], [0.0]])
    for i in range(2):
        for j in range(4):
            changes[i][0] += first_two_term_from_error[j][0] * output0[j][i]


    weights = weights - lr*changes
    bias_change = 0.0
    for j in range(4):
        bias_change += first_two_term_from_error[j][0] * 1
    bias = bias - lr*bias_change
    
output  = sig(np.dot(x, weights)+bias)
weights,bias,output

(array([[5.46656719],
        [5.46656719]]), array([-8.29260022]), array([[2.50299951e-04],
        [5.59335046e-02],
        [5.59335047e-02],
        [9.33425166e-01]]))

In [11]:
for iter in range(10000):
    output0 =x
    output = sig(np.dot(output0, weights)+bias)

    first_term = output - y
    input_for_last_layer = np.dot(output0, weights)+bias
    second_term = derivativeSig(input_for_last_layer)
    first_two_term_from_error = first_term * second_term

    changes = np.dot(output0.T, first_two_term_from_error)
  

    weights = weights - lr*changes
    bias_change = np.sum(first_two_term_from_error)
    

    bias = bias - lr*bias_change
    
output  = sig(np.dot(x, weights)+bias)
weights,bias,output

(array([[5.48035229],
        [5.48035227]]), array([-8.31321643]), array([[2.45193798e-04],
        [5.55738801e-02],
        [5.55738813e-02],
        [9.33856005e-01]]))